//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoCeHealthLive
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraxiCenterEntities : DbContext
    {
        public PraxiCenterEntities()
            : base("name=PraxiCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TadrPersonen> TadrPersonen { get; set; }
        public virtual DbSet<TadrStamm> TadrStamm { get; set; }
        public virtual DbSet<TpatNummer> TpatNummer { get; set; }
    }
}
