//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoCeHealthLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpatNummer
    {
        public int IDPatientenNummer { get; set; }
        public int inPatientID { get; set; }
        public int inZugriffsmandantID { get; set; }
        public int inNummer { get; set; }
        public int inLastUpdateUser { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
        public int inCreationUser { get; set; }
        public System.DateTime dtCreation { get; set; }
        public byte[] timestamp { get; set; }
    }
}
